
export const GET_CHARACTERS = "GET_CHARACTERS";
export const GET_CHARACTER = "GET_CHARACTER";
export const GET_FILTER_GENDER = "GET_FILTER_GENDER";
export const GET_SEARCH = "GET_SEARCH";
export const ADD_FAVORITE = "ADD_FAVORITE";



